# Generated by Django 4.0.1 on 2022-12-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fpass_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_payment_apcepted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_payment_done',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_team_registration_done',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='t_shirt_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upcomming_event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upcomming_event_venue',
        ),
    ]
