# Generated by Django 4.0.1 on 2022-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_user_fpass_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(default='roy', max_length=100),
        ),
    ]
