# Generated by Django 4.0.1 on 2022-12-09 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_f_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('t10t11', models.IntegerField(default=20)),
                ('t11t12', models.IntegerField(default=20)),
                ('t12t1', models.IntegerField(default=20)),
                ('t1t2', models.IntegerField(default=20)),
                ('t2t3', models.IntegerField(default=20)),
                ('t3t4', models.IntegerField(default=20)),
                ('t4t5', models.IntegerField(default=20)),
                ('t5t6', models.IntegerField(default=20)),
                ('t6t7', models.IntegerField(default=20)),
                ('t7t8', models.IntegerField(default=20)),
                ('t8t9', models.IntegerField(default=20)),
                ('t9t10', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.IntegerField()),
                ('t_id', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
