# Generated by Django 4.0.1 on 2022-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
