# Generated by Django 4.0.1 on 2022-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_booking_payment_method_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='total_sell',
            field=models.IntegerField(default=0),
        ),
    ]
