# Generated by Django 4.0.1 on 2022-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_order_is_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_payment_done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
