# Generated by Django 4.0.1 on 2022-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_order_is_food_ready_order_is_food_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
