# Generated by Django 4.0.1 on 2022-12-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_food_modifyed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpn_code', models.CharField(max_length=15)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cpn_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
